### ISSUE TITLE
Failure loading libblastrampoline on julia v1.9

### ISSUE THREAD

**Issue by baggepinnen** [andreasvarga/MatrixPencils.jl#11]
Hello Andreas, hope you're doing well!

A user of ControlSystems.jl [recently reported](https://github.com/JuliaControl/ControlSystems.jl/issues/834) an error calling `lsminreal` in Julia v1.9 running on Windows. 
The error looks like this
![error](https://user-images.githubusercontent.com/54220415/237636414-d3edf7f2-e8cd-4797-8539-6275a870038b.png)

(`minreal` is a thin wrapper around `MatrixPencils.lsminreal`)

I suspect the error stems from some manual management of the lapack installation in this package, a search came up with this line mentioning libblastrampoline explicitly
https://github.com/andreasvarga/MatrixPencils.jl/blob/460e14a529b7c300dca4917cefcca94e5d0c0ee5/src/lapackutil2.jl#L3

**Comment by andreasvarga** [comment]
I already mentioned this issue [here](https://github.com/JuliaLang/julia/issues/47638#issuecomment-1441482617). My hope was that it will be automatically addressed with Julia 1.9, but apparently it was not. Any proposal how to proceed further with this?

**Comment by baggepinnen** [comment]
[This comment](https://github.com/JuliaLang/julia/issues/47638#issuecomment-1441522156)
> It is not, that's the reason why we have Base.libblas_name: https://github.com/JuliaLang/julia/pull/48435.

makes me think that this line 
https://github.com/andreasvarga/MatrixPencils.jl/blob/460e14a529b7c300dca4917cefcca94e5d0c0ee5/src/lapackutil2.jl#L3

should remove the version check and always use `Base.liblapack_name`, since this variable will have the correct value for all OS platforms, see [here](https://github.com/JuliaLang/julia/pull/48435/files#diff-552535418914ef7bb1ebe851ebb5bdd5c1485570a1b4c24ffa42a8d90aa972deR291)

**Comment by andreasvarga** [comment]
Thanks. I implemented your proposal and performed exhaustive tests for Julia 1.6-1.10 on both Windows and Linux. The version v1.7.7 will fix this problem for all Julia versions.

The same modification needs to be also performed to MatrixEquations.

**Comment by baggepinnen** [comment]
Thanks for fixing!
