### ISSUE TITLE
Compat with Polynomials v4?

### ISSUE THREAD

**Issue by baggepinnen** [andreasvarga/MatrixPencils.jl#13]
[Polynomials.jl realeased a new major version a while back](https://github.com/JuliaMath/Polynomials.jl/releases/tag/v4.0.0), and I'm currently facing some compatibility problems in our stack due to MatrixPencils not supporting this new version. Would it be possible to add compat for Polynomials v4?

**Comment by andreasvarga** [comment]
I will check what has to be fixed. Just now I have no possibility to make any update, being in a short vacancy until Sep. 9.

**Comment by baggepinnen** [comment]
Hopefully there shouldn't be anything that requires updating. I can submit a PR that bumps the compat and we can see whether or not the tests pass.

Enjoy your vacation :)
