### ISSUE TITLE
Is this of any help...

### ISSUE THREAD

**Issue by jverzani** [andreasvarga/MatrixPencils.jl#7]
Hi, I started sketching out a package for Rational Functions based on Polynomials. The code is here https://github.com/jverzani/PolynomialRatios.jl . I don't know if it is helpful to you, but I could replicate the RationalFunctions code you have and include the transfer function type as a subtype of `AbtractRationalFunction`. Were I to do so, would I just include the methods you've defined in https://github.com/andreasvarga/DescriptorSystems.jl/blob/main/src/types/RationalFunction.jl or are there more  elsewhere in the code base?

**Comment by andreasvarga** [comment]
Concatenations are considered in the function rational_concatenations.jl.

john verzani ***@***.***> schrieb am Di., 23. März 2021,
01:09:
